### ISSUE TITLE
Creating Multiple Worksheets in single XLS file

### ISSUE THREAD

**Issue by exceptionraiser** [arydjmal/to_xls#4]
Just wondering if it's still possible to do this. It looks like it was possible when you did this http://arydjmal.com/2008/6/8/export-to-excel-in-rails-2. But is it possible to do with the current gem? If so, how would I go about this.

Thanks!

**Comment by arydjmal** [comment]
No, it is not possible using the plugin.

**Comment by exceptionraiser** [comment]
Is it possible though outside of this gem? Anything you know of?

Thanks

On Tue, Jan 17, 2012 at 9:27 PM, Ary Djmal
reply@reply.github.com
wrote:

**Comment by arydjmal** [comment]
Yes, one way could be doing it manually like my blog post, look at index.xls.builder.

**Comment by exceptionraiser** [comment]
ok cool that's what i figured. thanks man

On Tue, Jan 17, 2012 at 9:35 PM, Ary Djmal
reply@reply.github.com
wrote:
