### ISSUE TITLE
array.to_xls

### ISSUE THREAD

**Issue by kingM** [arydjmal/to_xls#5]
array = Array.new

for p in post
item = Hash.new
item["id"] = p.id
item["name"] = p.name
array << item
end

send_data array.to_xls

not work help

**Comment by arydjmal** [comment]
Why would you do something like that?

posts.to_xls(:only => [:id, :name]) 

-Ary

**Comment by kingM** [comment]
tks 

array = Array.new

for p in post
comment = Coment.where('post_id = ?', post.id).frist
item = Hash.new
item["id"] = p.id
item["name"] = p.name
item["title comment"] = comment.title
array << item
end

send_data array.to_xls

not work
